//! Connector API-doc change watcher — the DETECTION stage of Personas' curated
//! connector-update events.
//!
//! Once a month it fetches the public API-docs page of every Personas connector
//! listed in the watch manifest (`catalog/connector-docs.json`, generated by
//! `personas/scripts/events/generate-connector-events.mjs`), converts it to
//! Markdown, and upserts it into the change-detected `connector_docs` dataset.
//! For any doc that **changed** since last run it computes a line-level diff and
//! (by default) has the Claude engine summarize *what* changed for a developer.
//!
//! The result — `data/artifacts/connector-api-watch/<job>/changes.json` — is the
//! hand-off to the DISTRIBUTION stage: the dev copies it into personas and runs
//! `generate-connector-events.mjs --changes changes.json`, which bakes the
//! changes into `builtin_shared_events.rs` and ships them in the next release.
//! See `personas/docs/plans/curated-connector-events.md`.
//!
//! Params (all optional):
//!   { "manifest": "catalog/connector-docs.json",  // watch list path
//!     "summarize": true,   // run the Claude diff-summary pass on changes
//!     "limit": 0,          // cap connectors scanned this run (0 = all)
//!     "only": ["elevenlabs","stripe"] }  // restrict to these connector slugs

use std::collections::BTreeSet;

use async_trait::async_trait;
use pumper_core::datasets::ChangeKind;
use pumper_core::fetcher::FetchRequest;
use pumper_core::{AppContext, Error, ResearchOutput, ResearchRequest, Result, ScrapeApp};
use serde::Deserialize;
use serde_json::{json, Value};
use sha2::{Digest, Sha256};

const DATASET: &str = "connector_docs";
const DEFAULT_MANIFEST: &str = "catalog/connector-docs.json";
/// Cap the diff fed to Claude so a large doc rewrite can't blow up the prompt.
const MAX_DIFF_LINES: usize = 200;
const MAX_DIFF_CHARS: usize = 6000;

#[derive(Debug, Deserialize)]
struct Manifest {
    #[serde(default)]
    connectors: Vec<ManifestEntry>,
}

#[derive(Debug, Deserialize, Clone)]
struct ManifestEntry {
    slug: String,
    #[serde(default)]
    label: String,
    docs_url: String,
}

pub struct ConnectorApiWatch;

#[async_trait]
impl ScrapeApp for ConnectorApiWatch {
    fn name(&self) -> &'static str {
        "connector-api-watch"
    }

    fn description(&self) -> &'static str {
        "Monthly watcher over Personas connectors' public API docs. Diffs each \
         docs page against last run and Claude-summarizes what changed. Emits \
         changes.json for the personas event-seed bridge. Params: \
         {\"manifest\": \"catalog/connector-docs.json\", \"summarize\": true, \
         \"limit\": 0, \"only\": [\"elevenlabs\"]}"
    }

    /// 06:00 UTC on the 1st of each month.
    fn schedule(&self) -> Option<&'static str> {
        Some("0 0 6 1 * *")
    }

    fn default_params(&self) -> Value {
        json!({ "manifest": DEFAULT_MANIFEST, "summarize": true, "limit": 0 })
    }

    async fn run(&self, ctx: AppContext) -> Result<Value> {
        let manifest_path = ctx
            .params
            .get("manifest")
            .and_then(Value::as_str)
            .unwrap_or(DEFAULT_MANIFEST)
            .to_string();
        let summarize = ctx
            .params
            .get("summarize")
            .and_then(Value::as_bool)
            .unwrap_or(true);
        let limit = ctx.params.get("limit").and_then(Value::as_u64).unwrap_or(0) as usize;
        let only: Option<BTreeSet<String>> =
            ctx.params.get("only").and_then(Value::as_array).map(|a| {
                a.iter()
                    .filter_map(Value::as_str)
                    .map(|s| s.to_string())
                    .collect()
            });

        let raw = std::fs::read_to_string(&manifest_path)
            .map_err(|e| Error::App(format!("read manifest {manifest_path}: {e}")))?;
        let manifest: Manifest = serde_json::from_str(&raw)
            .map_err(|e| Error::App(format!("parse manifest {manifest_path}: {e}")))?;

        let mut scanned = 0usize;
        let mut changed = 0usize;
        let mut errors: Vec<Value> = Vec::new();
        let mut changes: Vec<Value> = Vec::new();

        for entry in &manifest.connectors {
            if let Some(ref set) = only {
                if !set.contains(&entry.slug) {
                    continue;
                }
            }
            if limit > 0 && scanned >= limit {
                break;
            }
            scanned += 1;

            // Prior content (for diffing) BEFORE we upsert the new content.
            let prior_markdown = match ctx.datasets.get(&ctx.app, DATASET, &entry.slug).await {
                Ok(Some(rec)) => rec
                    .data
                    .get("markdown")
                    .and_then(Value::as_str)
                    .map(String::from),
                _ => None,
            };

            let outcome = match ctx
                .engines
                .fetch
                .fetch(FetchRequest {
                    url: entry.docs_url.clone(),
                    to_markdown: true,
                    ..FetchRequest::new(&entry.docs_url)
                })
                .await
            {
                Ok(o) => o,
                Err(e) => {
                    tracing::warn!(slug = %entry.slug, "fetch failed: {e}");
                    errors.push(json!({ "connector": entry.slug, "error": e.to_string() }));
                    continue;
                }
            };
            let markdown = outcome.markdown.clone().unwrap_or_default();
            if markdown.trim().is_empty() {
                errors.push(json!({ "connector": entry.slug, "error": "empty document" }));
                continue;
            }
            let hash = sha256(&markdown);

            let record = json!({
                "docs_url": entry.docs_url,
                "label": entry.label,
                "hash": hash,
                "markdown": markdown,
                "engine": outcome.engine,
            });
            let kind = ctx
                .upsert(DATASET, &entry.slug, &record)
                .await
                .unwrap_or(ChangeKind::Unchanged);

            // Only a CHANGED record (not a first-seen baseline) is a real event.
            if kind != ChangeKind::Changed {
                continue;
            }
            let Some(prev) = prior_markdown else { continue };
            let (added, removed) = line_diff(&prev, &markdown);
            if added.is_empty() && removed.is_empty() {
                continue; // hash flipped on noise (whitespace/reorder) — not substantive
            }
            changed += 1;

            let detected_at = chrono::Utc::now().to_rfc3339();
            let (summary, tags, severity) = if summarize {
                summarize_change(&ctx, entry, &added, &removed)
                    .await
                    .unwrap_or_else(|e| {
                        tracing::warn!(slug = %entry.slug, "summarize failed: {e}");
                        (
                            fallback_summary(&added, &removed),
                            Vec::new(),
                            "minor".into(),
                        )
                    })
            } else {
                (
                    fallback_summary(&added, &removed),
                    Vec::new(),
                    "minor".into(),
                )
            };

            changes.push(json!({
                "connector": entry.slug,
                "label": entry.label,
                "docs_url": entry.docs_url,
                "detected_at": detected_at,
                "summary": summary,
                "tags": tags,
                "severity": severity,
                "lines_added": added.len(),
                "lines_removed": removed.len(),
            }));
        }

        let result = json!({
            "scanned": scanned,
            "changed": changed,
            "changes": changes,
            "errors": errors,
        });
        ctx.save_artifact("changes.json", &serde_json::to_vec_pretty(&result)?)
            .await?;
        Ok(result)
    }
}

fn sha256(s: &str) -> String {
    let mut h = Sha256::new();
    h.update(s.as_bytes());
    hex::encode(h.finalize())
}

/// Naive set-based line diff: lines present in `new` but not `old` (added) and
/// vice-versa (removed), order-preserved, bounded. Good enough to feed a
/// summarizer — we want "what appeared / disappeared", not a minimal edit script.
fn line_diff(old: &str, new: &str) -> (Vec<String>, Vec<String>) {
    let norm = |s: &str| s.trim().to_string();
    let old_set: BTreeSet<String> = old.lines().map(norm).filter(|l| !l.is_empty()).collect();
    let new_set: BTreeSet<String> = new.lines().map(norm).filter(|l| !l.is_empty()).collect();
    let added: Vec<String> = new
        .lines()
        .map(norm)
        .filter(|l| !l.is_empty() && !old_set.contains(l))
        .take(MAX_DIFF_LINES)
        .collect();
    let removed: Vec<String> = old
        .lines()
        .map(norm)
        .filter(|l| !l.is_empty() && !new_set.contains(l))
        .take(MAX_DIFF_LINES)
        .collect();
    (added, removed)
}

fn clamp(lines: &[String]) -> String {
    let mut out = String::new();
    for l in lines {
        if out.len() + l.len() + 1 > MAX_DIFF_CHARS {
            break;
        }
        out.push_str(l);
        out.push('\n');
    }
    out
}

fn fallback_summary(added: &[String], removed: &[String]) -> String {
    format!(
        "API documentation changed: {} line(s) added, {} line(s) removed. Review the docs for details.",
        added.len(),
        removed.len()
    )
}

/// Builds the diff-summary request.
///
/// Extracted so the request's *cacheability* is a testable property, not an
/// accident of the call site: it carries no `resume_session`, so
/// [`AppContext::research`]'s disk cache keys on the (label, diff) content and a
/// re-run over an unchanged diff costs nothing. `max_turns = 1` keeps a
/// summarizer from turning into an agent loop.
fn change_summary_request(label: &str, added: &[String], removed: &[String]) -> ResearchRequest {
    let prompt = format!(
        "You are reviewing a diff of the public API documentation for the '{label}' \
         service. Below are lines ADDED and REMOVED since the last check. Summarize, \
         for a developer who integrates with this API, what materially changed \
         (new/removed/renamed endpoints, auth changes, parameter or field changes, \
         rate-limit or versioning changes). Ignore cosmetic/marketing/navigation \
         churn.\n\n\
         ADDED:\n{}\n\nREMOVED:\n{}\n\n\
         Respond with ONLY a JSON object (no prose, no fences):\n\
         {{\"summary\": string (<=280 chars, empty string if no material change), \
         \"tags\": string[] (subset of [\"new_endpoint\",\"removed_endpoint\",\
         \"auth_change\",\"param_change\",\"versioning\",\"rate_limit\",\"deprecation\",\
         \"breaking\"]), \"severity\": \"patch\"|\"minor\"|\"major\"|\"breaking\"}}",
        clamp(added),
        clamp(removed),
    );

    let mut req = ResearchRequest::new(prompt).with_role("research");
    req.max_turns = Some(1);
    req
}

/// Parses the summarizer's answer into `{ summary, tags[], severity }`.
///
/// Extracted from the `research` call so the "model said nothing material" and
/// "model returned prose instead of JSON" paths are directly testable without a
/// model. Anything unparseable degrades to the deterministic
/// [`fallback_summary`] rather than emitting an empty change event.
fn parse_summary_response(
    out: &ResearchOutput,
    added: &[String],
    removed: &[String],
) -> (String, Vec<String>, String) {
    let v = out
        .json
        .clone()
        .unwrap_or_else(|| Value::String(out.text.clone()));

    let summary = v
        .get("summary")
        .and_then(Value::as_str)
        .unwrap_or("")
        .trim()
        .to_string();
    if summary.is_empty() {
        // Model judged the diff immaterial — surface a neutral fallback so the
        // firing still carries something, but tag it low severity.
        return (fallback_summary(added, removed), vec![], "patch".into());
    }
    let tags: Vec<String> = v
        .get("tags")
        .and_then(Value::as_array)
        .map(|a| {
            a.iter()
                .filter_map(Value::as_str)
                .map(String::from)
                .collect()
        })
        .unwrap_or_default();
    let severity = v
        .get("severity")
        .and_then(Value::as_str)
        .unwrap_or("minor")
        .to_string();
    (summary, tags, severity)
}

/// Claude-summarize a doc diff into `{ summary, tags[], severity }`.
///
/// Goes through [`AppContext::research`] — the metered chokepoint — **not**
/// `engines.claude`: this call site used to reach the engine directly, so every
/// doc-diff summary ran uncached, unbudgeted and invisible to the cost ledger.
/// Through the wrapper an unchanged diff is served from the research cache at
/// zero cost, the per-call ceiling is clamped to the job's remaining headroom,
/// and a budget-exhausted job returns `Err` here — which the caller already
/// degrades to [`fallback_summary`] rather than failing the whole watch run.
async fn summarize_change(
    ctx: &AppContext,
    entry: &ManifestEntry,
    added: &[String],
    removed: &[String],
) -> Result<(String, Vec<String>, String)> {
    let label = if entry.label.is_empty() {
        entry.slug.as_str()
    } else {
        entry.label.as_str()
    };
    let out = ctx
        .research(change_summary_request(label, added, removed))
        .await?;
    Ok(parse_summary_response(&out, added, removed))
}

#[cfg(test)]
mod tests {
    use super::*;

    // Realistic slices of an API docs page fetched as markdown, before and
    // after an endpoint was replaced (Stripe-style endpoint listing).
    const OLD_DOC: &str = "# Payments API\n\n## Endpoints\n\n- POST /v1/charges\n- GET /v1/charges/:id\n\nRate limit: 100 req/min\n";
    const NEW_DOC: &str = "# Payments API\n\n## Endpoints\n\n- POST /v1/payment_intents\n- GET /v1/charges/:id\n\nRate limit: 100 req/min\n";

    #[test]
    fn line_diff_reports_appeared_and_disappeared_lines_not_the_whole_doc() {
        let (added, removed) = line_diff(OLD_DOC, NEW_DOC);
        assert_eq!(added, vec!["- POST /v1/payment_intents"]);
        assert_eq!(removed, vec!["- POST /v1/charges"]);
    }

    #[test]
    fn whitespace_reflow_and_reorder_is_noise_not_a_change() {
        // Same lines re-indented and reordered: the content hash flips, but the
        // diff must come back empty so no change event fires.
        let reflowed = "  # Payments API\n## Endpoints\n- GET /v1/charges/:id\n- POST /v1/charges\n\nRate limit: 100 req/min\n";
        let (added, removed) = line_diff(OLD_DOC, reflowed);
        assert!(added.is_empty(), "reflow produced added lines: {added:?}");
        assert!(
            removed.is_empty(),
            "reflow produced removed lines: {removed:?}"
        );
    }

    #[test]
    fn full_rewrite_diff_is_bounded_not_unbounded() {
        // A large doc rewrite must not blow up the summarizer prompt.
        let new: String = (0..500).map(|i| format!("line {i}\n")).collect();
        let (added, removed) = line_diff("", &new);
        assert_eq!(added.len(), MAX_DIFF_LINES);
        assert!(removed.is_empty());
    }

    #[test]
    fn clamp_cuts_at_whole_lines_within_the_char_budget() {
        let lines: Vec<String> = (0..500)
            .map(|i| format!("added endpoint number {i} with a longer description"))
            .collect();
        let out = clamp(&lines);
        assert!(out.len() <= MAX_DIFF_CHARS);
        // Every emitted line is complete — no truncated mid-line fragment.
        assert!(out.ends_with('\n'));
        assert!(out.lines().all(|l| lines.iter().any(|src| src == l)));
    }

    fn diff() -> (Vec<String>, Vec<String>) {
        line_diff(OLD_DOC, NEW_DOC)
    }

    /// A `ResearchOutput` carrying `text`, with `json` populated exactly the way
    /// the real engine populates it (present only when the answer parses).
    fn answer(text: &str) -> ResearchOutput {
        ResearchOutput {
            text: text.to_string(),
            json: serde_json::from_str(text).ok(),
            cost_usd: Some(0.0),
            duration_ms: Some(0),
            num_turns: Some(1),
            session_id: None,
        }
    }

    #[test]
    fn summary_request_is_cacheable_not_a_resumed_session() {
        // `AppContext::research` deliberately bypasses its disk cache for
        // resumed sessions. This is a one-shot summarizer, so leaving
        // `resume_session` unset is what makes a re-run over an unchanged diff
        // free — the whole point of routing it through the chokepoint.
        let (added, removed) = diff();
        let req = change_summary_request("Stripe", &added, &removed);
        assert!(
            req.resume_session.is_none(),
            "a resumed session opts out of the research cache"
        );
        // A summarizer must not become an agent loop, and it must run on the
        // cheap preset rather than the compose one.
        assert_eq!(req.max_turns, Some(1));
        assert_eq!(req.role.as_deref(), Some("research"));
    }

    #[test]
    fn summary_request_carries_the_diff_not_just_the_connector_name() {
        // Grounding: the model must see the actual changed lines. A prompt that
        // only names the connector produces a plausible, invented summary.
        let (added, removed) = diff();
        let req = change_summary_request("Stripe", &added, &removed);
        assert!(req.prompt.contains("Stripe"));
        assert!(req.prompt.contains("- POST /v1/payment_intents"));
        assert!(req.prompt.contains("- POST /v1/charges"));
    }

    #[test]
    fn identical_diffs_build_identical_requests_so_the_cache_can_hit() {
        // `ResearchCache::key` hashes the request; a prompt carrying anything
        // per-run (a timestamp, a job id) would make every call a cache miss.
        let (added, removed) = diff();
        assert_eq!(
            change_summary_request("Stripe", &added, &removed).prompt,
            change_summary_request("Stripe", &added, &removed).prompt,
        );
    }

    #[test]
    fn prose_answer_degrades_to_the_fallback_not_an_empty_summary() {
        // The model ignored "JSON only" and answered in prose: no `summary`
        // key, so the deterministic fallback carries the event instead of an
        // empty string reaching the changes.json hand-off.
        let (added, removed) = diff();
        let out = answer("Sure! Here is what changed: ...");
        let (summary, tags, severity) = parse_summary_response(&out, &added, &removed);
        assert!(summary.contains("1 line(s) added"));
        assert!(tags.is_empty());
        assert_eq!(severity, "patch");
    }

    #[test]
    fn immaterial_change_is_tagged_patch_not_dropped() {
        let (added, removed) = diff();
        let out = answer(r#"{"summary":"  ","tags":["breaking"],"severity":"breaking"}"#);
        let (summary, tags, severity) = parse_summary_response(&out, &added, &removed);
        assert!(summary.contains("API documentation changed"));
        assert!(tags.is_empty(), "an empty summary keeps no severity tags");
        assert_eq!(severity, "patch");
    }

    #[test]
    fn structured_answer_is_passed_through_intact() {
        let (added, removed) = diff();
        let out = answer(
            r#"{"summary":"POST /v1/charges replaced by POST /v1/payment_intents.",
                "tags":["new_endpoint","removed_endpoint","breaking"],
                "severity":"breaking"}"#,
        );
        let (summary, tags, severity) = parse_summary_response(&out, &added, &removed);
        assert_eq!(
            summary,
            "POST /v1/charges replaced by POST /v1/payment_intents."
        );
        assert_eq!(tags, ["new_endpoint", "removed_endpoint", "breaking"]);
        assert_eq!(severity, "breaking");
    }
}
