[package]
name = "app-research"
version.workspace = true
edition.workspace = true

[dependencies]
pumper-core.workspace = true
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
tokio.workspace = true
pumper-core = { workspace = true, features = ["test-support"] }
