// The SBOM generator's fixture suite.
//
// An SBOM is a document nobody reads until an advisory lands, which is exactly
// the shape of instrument that rots silently: a generator that silently emits
// zero components, or drops every checksum, looks identical to a working one
// from the outside. So the assertions below are about the failures that would be
// INVISIBLE — an empty document, a missing hash, an invented dependency edge, a
// purl claimed for a crate that was never published — plus one liveness check
// against the real Cargo.lock in this checkout.
//
// Run by `just sbom-test` and by the `Ship inventory` CI job.

import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';

import { CRATES_IO, buildSbom, depName, parseCargoLock, workspaceVersion } from './sbom.mjs';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(HERE, '../..');

const LOCK = `# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "serde"
version = "1.0.219"
source = "${CRATES_IO}"
checksum = "5f0e2c6ed6606019b4e29e69dbaba95b11854410e5347d525002456dbbb786b6"
dependencies = [
 "serde_derive",
]

[[package]]
name = "serde_derive"
version = "1.0.219"
source = "${CRATES_IO}"
checksum = "5b0276cf7f2c73365f7157c8123c21cd9a50fbbd844757af28ca1f5925fc2a00"

[[package]]
name = "pumper-core"
version = "0.1.0"
dependencies = [
 "serde",
]

[[patch.unused]]
name = "ghost"
version = "9.9.9"
`;

const CARGO_TOML = `[workspace]
resolver = "2"
members = ["crates/core"]

[workspace.package]
version = "0.1.0"
edition = "2021"
`;

test('the_lockfile_parser_reads_packages_not_patch_tables', () => {
  const { lockVersion, packages } = parseCargoLock(LOCK);
  assert.equal(lockVersion, 4);
  assert.deepEqual(
    packages.map((p) => p.name),
    ['serde', 'serde_derive', 'pumper-core'],
    'a [[patch.unused]] table is not a package and must not become a component'
  );
  assert.deepEqual(packages[0].dependencies, ['serde_derive']);
  assert.equal(packages[2].source, undefined, 'a workspace member has no source');
});

test('every_registry_crate_carries_its_checksum_not_just_its_name', () => {
  const sbom = buildSbom({ lockText: LOCK, cargoTomlText: CARGO_TOML });
  const serde = sbom.components.find((c) => c.name === 'serde');
  assert.deepEqual(serde.hashes, [
    { alg: 'SHA-256', content: '5f0e2c6ed6606019b4e29e69dbaba95b11854410e5347d525002456dbbb786b6' },
  ]);
  assert.equal(serde.purl, 'pkg:cargo/serde@1.0.219');
});

test('a_workspace_member_gets_no_purl_it_was_never_published', () => {
  const sbom = buildSbom({ lockText: LOCK, cargoTomlText: CARGO_TOML });
  const local = sbom.components.find((c) => c.name === 'pumper-core');
  assert.equal(local.purl, undefined);
  assert.equal(local.hashes, undefined);
  assert.deepEqual(local.properties, [{ name: 'cargo:source', value: 'workspace-member' }]);
});

test('an_unresolvable_edge_is_dropped_not_invented', () => {
  const withGhostDep = LOCK.replace('dependencies = [\n "serde",\n]', 'dependencies = [\n "serde",\n "nowhere",\n]');
  const sbom = buildSbom({ lockText: withGhostDep, cargoTomlText: CARGO_TOML });
  const core = sbom.dependencies.find((d) => d.ref === 'pumper-core@0.1.0');
  assert.deepEqual(core.dependsOn, ['serde@1.0.219']);
});

test('a_versioned_dependency_entry_resolves_to_that_version', () => {
  assert.equal(depName('serde 1.0.219 (registry+https://example.invalid)'), 'serde');
  assert.equal(depName('serde'), 'serde');
});

test('the_document_is_byte_stable_across_runs', () => {
  // Not decoration: a `serialNumber` or a `metadata.timestamp` would make two
  // SBOMs of the SAME lockfile differ, which makes "did the dependency set
  // change" unanswerable by diff and makes the release attestation describe a
  // moving target.
  const a = JSON.stringify(buildSbom({ lockText: LOCK, cargoTomlText: CARGO_TOML }));
  const b = JSON.stringify(buildSbom({ lockText: LOCK, cargoTomlText: CARGO_TOML }));
  assert.equal(a, b);
  assert.ok(!a.includes('serialNumber'));
  assert.ok(!a.includes('timestamp'));
});

test('the_metadata_component_names_the_shipped_binary', () => {
  const sbom = buildSbom({ lockText: LOCK, cargoTomlText: CARGO_TOML });
  assert.equal(sbom.bomFormat, 'CycloneDX');
  assert.equal(sbom.specVersion, '1.6');
  assert.equal(sbom.metadata.component.name, 'pumper');
  assert.equal(sbom.metadata.component.version, workspaceVersion(CARGO_TOML));
});

test('the_generator_actually_sees_this_repos_lockfile', () => {
  // Liveness. An empty or tiny document passes every assertion above for the
  // wrong reason, and is precisely what a moved file or a broken filter emits.
  const lockText = fs.readFileSync(path.join(REPO_ROOT, 'Cargo.lock'), 'utf8');
  const cargoTomlText = fs.readFileSync(path.join(REPO_ROOT, 'Cargo.toml'), 'utf8');
  const sbom = buildSbom({ lockText, cargoTomlText });
  assert.ok(
    sbom.components.length > 300,
    `only ${sbom.components.length} components — the generator is looking at the wrong file`
  );
  const hashed = sbom.components.filter((c) => c.hashes).length;
  assert.ok(
    hashed / sbom.components.length > 0.8,
    `only ${hashed}/${sbom.components.length} components carry a checksum — the parser dropped them`
  );
  // The workspace's own crates must be IN it: a bill of materials for the
  // binary that omits the binary's own crates is describing something else.
  const names = new Set(sbom.components.map((c) => c.name));
  for (const crate of ['pumper-core', 'pumper-server', 'pumper-engine-wasm']) {
    assert.ok(names.has(crate), `${crate} is missing from the SBOM`);
  }
});
